env:
  es2022: true
  browser: true

parserOptions:
  ecmaVersion: latest
  sourceType: 'module'
  ecmaFeatures:
    jsx: true

extends: [
  'eslint:recommended',
  'plugin:react/recommended',
  'plugin:react-hooks/recommended',
  'htmlacademy/react'
]

plugins: [ 'react','react-refresh' ]

settings:
  react:
    version: 'detect'

rules:
  react-refresh/only-export-components: 'warn'
